MERGE INTO EMPLOYEE T
USING (SELECT 1 AS ID, 'Ritish' AS NAME, 50000 AS SALARY) S
ON T.ID = S.ID
WHEN MATCHED THEN
  UPDATE SET NAME = S.NAME, SALARY = S.SALARY
WHEN NOT MATCHED THEN
  INSERT (ID, NAME, SALARY) VALUES (S.ID, S.NAME, S.SALARY);
